"""
clients/kling_client.py — Phase 2: Kling O3 Pro video generation

Kling O3 Pro API schema (fal-ai/kling-video/o3/pro/image-to-video):
  image_url       string    — start frame URL
  end_image_url   string    — end frame URL (optional)
  prompt          string    — motion + voice_tone + lipsync dialogue
  duration        string    — DurationEnum: "3"–"15" (string, not int!)
  generate_audio  boolean   — native audio + lipsync
  multi_prompt    list      — multi-shot: [{prompt, duration}, ...]
  shot_type       enum      — "customize" | "intelligent"

❌ NOT in O3 schema: negative_prompt, cfg_scale, aspect_ratio, voice_ids
   Those exist only on V1/V2/V3 models.

Prompt construction for 15s (30-100 word sweet spot):
  "{trimmed_motion}. [Subject, {voice_tone}]: \"{script}\""
  Combined must stay ≤ 100 words to avoid chaotic rushed movement.
  The bracket format [Subject, voice_tone] is Kling's native lipsync trigger.

Audio:
  - Native lipsync via generate_audio=True
  - Voice style controlled via voice_tone descriptor in prompt
  - English: preserve natural capitalization for TTS inflection
  - Chinese: keep original case
"""

import os
import fal_client

from config import (
    FAL_KEY,
    KLING_O3_MODEL,
    KLING_O3_PRICING,
    OUTPUT_DIR,
)
from utils import emit_log, image_to_data_uri
from clients.imagekit_client import persist_from_url


# Word limits for the combined prompt (motion + voice_tone + script)
MOTION_WORD_CAP   = 100   # Max words for motion before trimming
COMBINED_WORD_CAP = 150  # Kling O3 safe limit: 150 words total (75 motion + 20 tone + 45 script)


class KlingClient:
    def __init__(self, session_id: str):
        self.session_id = session_id
        os.environ["FAL_KEY"] = FAL_KEY

    def generate(
        self,
        image_url: str,
        motion_prompt: str,
        video_script: str,
        duration: int,
        voice_tone: str = "speaks enthusiastically",
        session_id: str = None,
        aspect_ratio: str = None,   # kept for API compat — O3 ignores it (inherited from image)
        voice_language: str = None,
        product_name: str = None,   # preserved in original casing; rest lowercased for TTS naturalness
    ) -> tuple:
        """
        Generate video with native audio + lipsync using Kling O3 Pro.
        Returns (local_file_path, video_url).

        voice_tone: how the voice sounds, e.g. "speaks with energetic enthusiasm"
                    Generated by LLM based on product type + script energy.
        """
        sid = session_id or self.session_id

        # Convert local image to data URI if needed
        if not image_url.startswith(("http://", "https://", "data:")) and os.path.exists(image_url):
            emit_log(sid, "info", "📦 Converting local portrait to data URI...")
            image_url = image_to_data_uri(image_url)

        # ── Prompt construction ───────────────────────────────────────
        # O3 sweet spot: 30–100 words total
        # Motion is trimmed to 42 words max to leave room for script
        # Pattern: "{motion}, {voice_tone} and says "{script}""

        # 1. Trim motion prompt to MOTION_WORD_CAP words
        motion_words = motion_prompt.split()
        if len(motion_words) > MOTION_WORD_CAP:
            motion_words = motion_words[:MOTION_WORD_CAP]
            emit_log(sid, "info", f"✂️  Motion trimmed to {MOTION_WORD_CAP} words for O3 pacing")
        trimmed_motion = " ".join(motion_words).rstrip(",. ")
        motion_word_count = len(trimmed_motion.split())
        motion_status = "✅" if 70 <= motion_word_count <= 80 else ("⚠️ TOO SHORT" if motion_word_count < 70 else "⚠️ TOO LONG")
        emit_log(sid, "info", f"🎥 Motion prompt: {motion_word_count} words {motion_status} (target: 70–80)")
        emit_log(sid, "info", f"🎥 Motion: {trimmed_motion}")

        # 2. Determine audio mode
        if voice_language == "" or not video_script:
            # Silent mode — no lipsync
            full_prompt   = trimmed_motion
            generate_audio = False
            cost_mode      = "audio_off"
        else:
            # Audio + lipsync mode
            if voice_language == "zh":
                script_text = video_script                # Chinese — keep original
                emit_log(sid, "info", "🎙️ Voice language: Chinese")
            else:
                # Lowercase everything for natural TTS flow, then restore product name casing
                script_lower = video_script.lower()
                if product_name:
                    # Case-insensitive replace of product name back to its original casing
                    import re
                    script_lower = re.sub(
                        re.escape(product_name.lower()),
                        product_name,
                        script_lower,
                        flags=re.IGNORECASE
                    )
                script_text = script_lower
                emit_log(sid, "info", "🎙️ Voice language: English (lowercase + product name preserved)")

            # Build full prompt — Kling's native lipsync bracket syntax:
            # "{motion}. [Subject, {voice_tone}]: \"{script}\""
            # The [Subject, ...]: bracket is the official Kling lipsync trigger.
            # Without it, Kling drops the audio and generates a silent video.
            full_prompt    = f'{trimmed_motion}. [Subject, {voice_tone}]: "{script_text}"'
            generate_audio = True
            cost_mode      = "audio_on"

        # 3. Safety: enforce combined word cap
        total_words = len(full_prompt.split())
        if total_words > COMBINED_WORD_CAP:
            emit_log(sid, "warning",
                     f"⚠️  Combined prompt {total_words} words > {COMBINED_WORD_CAP} cap — trimming motion further")
            # Trim motion down until combined is under cap
            excess = total_words - COMBINED_WORD_CAP
            motion_words = motion_words[:max(20, len(motion_words) - excess)]
            trimmed_motion = " ".join(motion_words).rstrip(",. ")
            if generate_audio:
                full_prompt = f'{trimmed_motion}. [Subject, {voice_tone}]: "{script_text}"'
            else:
                full_prompt = trimmed_motion
            emit_log(sid, "info", f"✂️  Final prompt: {len(full_prompt.split())} words")

        # Duration: O3 requires integer on FAL wrapper to prevent silent fallbacks
        duration_int = min(int(duration), 15)   # cap at O3 max of 15

        cost = round(KLING_O3_PRICING.get(cost_mode, 0.168) * duration_int, 3)

        emit_log(sid, "processing", f"🎬 Phase 2: Generating video with Kling O3 Pro...")
        emit_log(sid, "info", f"Model: {KLING_O3_MODEL}")
        emit_log(sid, "info", f"Duration: {duration_int}s | Mode: {cost_mode} | Cost: ~${cost}")

        if generate_audio:
            emit_log(sid, "info", f"🎙️ Audio: Enabled (native O3 lipsync)")
            emit_log(sid, "info", f"🎭 Voice tone: {voice_tone}")
            script_words = len(video_script.split())
            emit_log(sid, "info", f"📝 Script ({script_words} words): {video_script}")
        else:
            emit_log(sid, "info", "🔇 Audio: Disabled (silent video)")

        emit_log(sid, "info", f"📋 Prompt ({len(full_prompt.split())} words): {full_prompt[:120]}...")

        # ── O3 API call ───────────────────────────────────────────────
        # Exact O3 Pro schema — only these 4 fields + optional end_image_url / multi_prompt
        arguments = {
            "image_url":      image_url,
            "prompt":         full_prompt,
            "duration":       duration_int,      # int: 5, 10, or 15
            "generate_audio": generate_audio,
            # NO negative_prompt  — not in O3 schema
            # NO cfg_scale        — not in O3 schema
            # NO aspect_ratio     — O3 inherits from input image
        }

        try:
            import time
            start_time = time.time()

            emit_log(sid, "processing", "📤 Submitting request to Kling O3 Pro...")

            handler = fal_client.submit(KLING_O3_MODEL, arguments=arguments)
            emit_log(sid, "success", "✓ Request submitted successfully")

            emit_log(sid, "processing", "⏳ Kling O3 Pro rendering video...")
            emit_log(sid, "info", "⏱️ Expected time: 3–8 minutes (O3 Pro generates 1080p)")
            emit_log(sid, "info", "📊 Progress updates will appear below...")

            result  = handler.get()
            elapsed = round(time.time() - start_time, 1)
            emit_log(sid, "success", f"✓ Video generated in {elapsed}s ({elapsed/60:.1f} min)")

            video = result.get("video")
            if isinstance(video, dict):
                video_url = video.get("url")
            else:
                video_url = video

            if not video_url:
                raise ValueError(f"No video URL in response: {result}")

            emit_log(sid, "success", "✓ Video generated")
            emit_log(sid, "info",    f"💰 Estimated cost: ${cost}")

            # Persist to ImageKit (falls back to local OUTPUT_DIR if ImageKit isn't configured)
            filename  = f"video_{sid}.mp4"
            save_path = persist_from_url(
                video_url, filename, subfolder="outputs",
                category="output", subtype="video", session_id=sid,
            )

            emit_log(sid, "success", f"✓ Video saved: {filename}")
            return save_path, video_url

        except Exception as e:
            emit_log(sid, "error", f"❌ Kling O3 error: {str(e)}")
            raise
